version: '2'
services:
  jwttoken-app:
    image: jwttoken
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://jwttoken-mysql:3306/jwttoken?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://jwttoken-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://jwttoken-elasticsearch:9200
    ports:
      - 8080:8080
  jwttoken-mysql:
    extends:
      file: mysql.yml
      service: jwttoken-mysql
  jwttoken-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: jwttoken-elasticsearch
